FROM rabbitmq:4.1

RUN apt-get update && \
    apt-get install -y wget && \
    wget -P /opt/rabbitmq/plugins/ https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.1.0/rabbitmq_delayed_message_exchange-4.1.0.ez && \
    rabbitmq-plugins enable --offline rabbitmq_management && \
    rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange